include lib/fonts/Makefile

# temporary one here until lib/vsprintf complete.
SRCS += lib/kstdio.c
SRCS += lib/vsprintf.c lib/string.c lib/ctype.c

CFLAGS_string.o += -fno-builtin-memset -fno-builtin-memcpyc